category: Lights, Camera
subcategory: Lights
description: "
Disable all lighting. Lighting is turned off by default and enabled with the lights() function. This function can be used to disable lighting so that 2D geometry (which does not require lighting) can be drawn after a set of lighted 3D geometry.
"
syntax: "noLights()"
related:
  - lights
