category: Math
subcategory: Bitwise Operators
description: "
Shifts bits to the left. The number to the left of the operator is shifted the number of places specified by the number to the right. Each shift to the left doubles the number, therefore each left shift multiplies the original number by 2. Use the left shift for fast multiplication or to pack a group of numbers together into one larger number. Left shifting only works with integers or numbers which automatically convert to an integer such as byte.
"
syntax: "<c>value</c> &lt;&lt; <c>n</c>"
parameters:
  - label: 'value'
    description: "int: the value to shift"
  - label: 'n'
    description: "int: the number of places to shift left"
related:
  - rightshift
