
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class ApplyMatrix0Test extends E2eTestBase {

  public ApplyMatrix0Test() {
    coreCodeTemplate = "P3D <- \"processing.opengl.PGraphics3D\"\nPI <- pi\n\nsettings <- function() {\n    size(100, 100, P3D)\n}\n\ndraw <- function() {\nnoFill()\ntranslate(50, 50, 0)\nrotateY(PI/6) \nstroke(153)\nbox(35)\n# Set rotation angles\nct = cos(PI/9.0)\nst = sin(PI/9.0)          \n# Matrix for rotation around the Y axis\napplyMatrix(  ct, 0.0,  st,  0.0,\n             0.0, 1.0, 0.0,  0.0,\n             -st, 0.0,  ct,  0.0,\n             0.0, 0.0, 0.0,  1.0)  \nstroke(255)\nbox(50)\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "https://processing.org/reference/images/applyMatrix_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
