
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Arc3Test extends E2eTestBase {

  public Arc3Test() {
    coreCodeTemplate = "# arc 3 https://processing.org/reference/arc_.html\n\narc(50, 50, 80, 80, 0, PI + QUARTER_PI, CHORD)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/arc_3.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
