
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BeginShape6Test extends E2eTestBase {

  public BeginShape6Test() {
    coreCodeTemplate = "beginShape(TRIANGLES)\nvertex(30, 75)\nvertex(40, 20)\nvertex(50, 75)\nvertex(60, 20)\nvertex(70, 75)\nvertex(80, 20)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/beginShape_5.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
