
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BeginShape5Test extends E2eTestBase {

  public BeginShape5Test() {
    coreCodeTemplate = "# beginShape 5 https://processing.org/reference/beginShape_.html\n\nnoFill()\nbeginShape()\nvertex(30, 20)\nvertex(85, 20)\nvertex(85, 75)\nvertex(30, 75)\nendShape(CLOSE)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/beginShape_4.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
