
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BeginShape11Test extends E2eTestBase {

  public BeginShape11Test() {
    coreCodeTemplate = "beginShape()\nvertex(20, 20)\nvertex(40, 20)\nvertex(40, 40)\nvertex(60, 40)\nvertex(60, 60)\nvertex(20, 60)\nendShape(CLOSE)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/beginShape_10.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
