
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BeginShape8Test extends E2eTestBase {

  public BeginShape8Test() {
    coreCodeTemplate = "beginShape(TRIANGLE_FAN)\nvertex(57.5, 50)\nvertex(57.5, 15)\nvertex(92, 50)\nvertex(57.5, 85)\nvertex(22, 50)\nvertex(57.5, 15)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/beginShape_7.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
