
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Bezier1Test extends E2eTestBase {

  public Bezier1Test() {
    coreCodeTemplate = "# bezier 1 https://processing.org/reference/bezier_.html\n\nnoFill()\nstroke(255, 102, 0)\nline(85, 20, 10, 10)\nline(90, 90, 15, 80)\nstroke(0, 0, 0)\nbezier(85, 20, 10, 10, 90, 90, 15, 80)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/bezier_0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
