
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BezierTangent2Test extends E2eTestBase {

  public BezierTangent2Test() {
    coreCodeTemplate = "# bezierTangent 2 https://processing.org/reference/bezierTangent_.html\n\nnoFill()\nbezier(85, 20, 10, 10, 90, 90, 15, 80)\nstroke(255, 102, 0)\nsteps <- 16\nfor (i in 0:steps) {\n    t <- i/steps\n    x <- bezierPoint(85, 10, 90, 15, t)\n    y <- bezierPoint(20, 10, 90, 80, t)\n    tx <- bezierTangent(85, 10, 90, 15, t)\n    ty <- bezierTangent(20, 10, 90, 80, t)\n    a <- atan2(ty, tx)\n    a <- a - HALF_PI\n    line(x, y, cos(a) * 8 + x, sin(a) * 8 + y)\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/bezierTangent_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
