
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class BezierVertex2Test extends E2eTestBase {

  public BezierVertex2Test() {
    coreCodeTemplate = "# bezierVertex 2 https://processing.org/reference/bezierVertex_.html\n\nbeginShape()\nvertex(30, 20)\nbezierVertex(80, 0, 80, 75, 30, 75)\nbezierVertex(50, 80, 60, 25, 30, 20)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/bezierVertex_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
