
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Bezier2Test extends E2eTestBase {

  public Bezier2Test() {
    coreCodeTemplate = "# bezier 2 https://processing.org/reference/bezier_.html\n\nnoFill()\nstroke(255, 102, 0)\nline(30, 20, 80, 5)\nline(80, 75, 30, 75)\nstroke(0, 0, 0)\nbezier(30, 20, 80, 5, 80, 75, 30, 75)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/bezier_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
