
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Color2Test extends E2eTestBase {

  public Color2Test() {
    coreCodeTemplate = "c = color(255, 204, 0)  # Define color 'c'\nfill(c)  # Use color variable 'c' as fill color\nnoStroke()  # Don't draw a stroke around shapes\nellipse(25, 25, 80, 80)  # Draw left circle\n\n# Using only one value with color() generates a grayscale value.\nc = color(65)  # Update 'c' with grayscale value\nfill(c)  # Use updated 'c' as fill color\nellipse(75, 75, 80, 80)  # Draw right circle\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/color_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
