
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class ColorMode2Test extends E2eTestBase {

  public ColorMode2Test() {
    coreCodeTemplate = "noStroke()\ncolorMode(HSB, 100)\nfor (i in 0:100) {\n    for (j in 0:100) {\n        stroke(i, j, 100)\n        point(i, j)\n    }\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/colorMode_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
