
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class CurveTangent1Test extends E2eTestBase {

  public CurveTangent1Test() {
    coreCodeTemplate = "# curveTangent 1 https://processing.org/reference/curveTangent_.html\n\nnoFill()\ncurve(5, 26, 73, 24, 73, 61, 15, 65)\nsteps <- 6\nfor (i in 0:steps) {\n    t <- i/steps\n    x <- curvePoint(5, 73, 73, 15, t)\n    y <- curvePoint(26, 24, 61, 65, t)\n    # ellipse(x, y, 5, 5)\n    tx <- curveTangent(5, 73, 73, 15, t)\n    ty <- curveTangent(26, 24, 61, 65, t)\n    a <- atan2(ty, tx)\n    a = a - HALF_PI\n    line(x, y, cos(a) * 8 + x, sin(a) * 8 + y)\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/curveTangent_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
