
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Curve1Test extends E2eTestBase {

  public Curve1Test() {
    coreCodeTemplate = "# curve 1 https://processing.org/reference/curve_.html\n\nnoFill()\nstroke(255, 102, 0)\ncurve(5, 26, 5, 26, 73, 24, 73, 61)\nstroke(0)\ncurve(5, 26, 73, 24, 73, 61, 15, 65)\nstroke(255, 102, 0)\ncurve(73, 24, 73, 61, 15, 65, 15, 65)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/curve_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
