
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class CurveVertex1Test extends E2eTestBase {

  public CurveVertex1Test() {
    coreCodeTemplate = "# curveVertex 1 https://processing.org/reference/curveVertex_.html\n\nnoFill()\nbeginShape()\ncurveVertex(84, 91)\ncurveVertex(84, 91)\ncurveVertex(68, 19)\ncurveVertex(21, 17)\ncurveVertex(32, 100)\ncurveVertex(32, 100)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/curveVertex_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
