
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class CurvePoint1Test extends E2eTestBase {

  public CurvePoint1Test() {
    coreCodeTemplate = "# curvePoint 1 https://processing.org/reference/curvePoint_.html\n\nnoFill()\ncurve(5, 26, 5, 26, 73, 24, 73, 61)\ncurve(5, 26, 73, 24, 73, 61, 15, 65)\nfill(255)\nellipseMode(CENTER)\n\nsteps <- 6\nfor (i in 0:steps) {\n    t <- i/steps\n    x <- curvePoint(5, 5, 73, 73, t)\n    y <- curvePoint(26, 26, 24, 61, t)\n    ellipse(x, y, 5, 5)\n    x <- curvePoint(5, 73, 73, 15, t)\n    y <- curvePoint(26, 24, 61, 65, t)\n    ellipse(x, y, 5, 5)\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/curvePoint_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
