
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class EllipseMode0Test extends E2eTestBase {

  public EllipseMode0Test() {
    coreCodeTemplate = "ellipseMode(RADIUS)  # Set ellipseMode to RADIUS\nfill(255)  # Set fill to white\nellipse(50, 50, 30, 30)  # Draw white ellipse using RADIUS mode\n\nellipseMode(CENTER)  # Set ellipseMode to CENTER\nfill(100)  # Set fill to gray\nellipse(50, 50, 30, 30)  # Draw gray ellipse using CENTER mode\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/ellipseMode_0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
