
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Green1Test extends E2eTestBase {

  public Green1Test() {
    coreCodeTemplate = "c = color(20, 75, 200)  # Define color 'c'\nfill(c)  # Use color variable 'c' as fill color\nrect(15, 20, 35, 60)  # Draw left rectangle\n\ngreenValue = green(c)  # Get green in 'c'\nprint(greenValue)  # Print '75.0'\nfill(0, greenValue, 0)  # Use 'greenValue' in new fill\nrect(50, 20, 35, 60)  # Draw right rectangle\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/green_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
