
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class LerpColor1Test extends E2eTestBase {

  public LerpColor1Test() {
    coreCodeTemplate = "stroke(255)\nbackground(51)\nfrom = color(204, 102, 0)\nto = color(0, 102, 153)\ninterA = lerpColor(from, to, 0.33)\ninterB = lerpColor(from, to, 0.66)\nfill(from)\nrect(10, 20, 20, 60)\nfill(interA)\nrect(30, 20, 20, 60)\nfill(interB)\nrect(50, 20, 20, 60)\nfill(to)\nrect(70, 20, 20, 60)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/lerpColor_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
