
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Lerp2Test extends E2eTestBase {

  public Lerp2Test() {
    coreCodeTemplate = "x1 = 15\ny1 = 10\nx2 = 80\ny2 = 90\nline(x1, y1, x2, y2)\nfor (i in 0:10) {\n    x = lerp(x1, x2, i/10) + 10\n    y = lerp(y1, y2, i/10)\n    point(x, y)\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/lerp_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
