
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class LightFalloff0Test extends E2eTestBase {

  public LightFalloff0Test() {
    coreCodeTemplate = "settings <- function() {\n    size(100, 100, P3D)\n}\n\ndraw <- function() {\n    noStroke()\n    background(0)\n    lightFalloff(1, 0.001, 0)\n    pointLight(150, 250, 150, 50, 50, 50)\n    beginShape()\n    vertex(0, 0, 0)\n    vertex(100, 0, -100)\n    vertex(100, 100, -100)\n    vertex(0, 100, 0)\n    endShape(CLOSE)\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "https://processing.org/reference/images/lightFalloff_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
