
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Line2Test extends E2eTestBase {

  public Line2Test() {
    coreCodeTemplate = "# line 2 https://processing.org/reference/line_.html\n\nline(30, 20, 85, 20)\nstroke(126)\nline(85, 20, 85, 75)\nstroke(255)\nline(85, 75, 30, 75)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/line_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
