
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Line3Test extends E2eTestBase {

  public Line3Test() {
    coreCodeTemplate = "# Drawing lines in 3D requires P3D as a parameter to size()\n\nP3D <- \"processing.opengl.PGraphics3D\"\n\nsettings <- function() {\n    size(100, 100, P3D)\n}\n\nsetup <- function() {\n}\n\ndraw <- function() {\n    line(30, 20, 0, 85, 20, 15)\n    stroke(126)\n    line(85, 20, 15, 85, 75, 0)\n    stroke(255)\n    line(85, 75, 0, 30, 75, -50)\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "https://processing.org/reference/images/line_2.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
