
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Mag1Test extends E2eTestBase {

  public Mag1Test() {
    coreCodeTemplate = "x1 = 20\nx2 = 80\ny1 = 30\ny2 = 70\n\nline(0, 0, x1, y1)\nprint(mag(x1, y1))  # Prints '36.05551'\nline(0, 0, x2, y1)\nprint(mag(x2, y1))  # Prints '85.44004'\nline(0, 0, x1, y2)\nprint(mag(x1, y2))  # Prints '72.8011'\nline(0, 0, x2, y2)\nprint(mag(x2, y2))  # Prints '106.30146'\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/mag_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
