
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class ModelX0Test extends E2eTestBase {

  public ModelX0Test() {
    coreCodeTemplate = "settings <- function() {\n    size(100, 100, P3D)\n}\n\ndraw <- function() {\n    noFill()\n    background(0)\n    pushMatrix()\n    # start at the middle of the screen\n    translate(width/2, height/2, -100)\n    # some random rotation to make things interesting\n    rotateY(1)  #yrot)\n    rotateZ(2)  #zrot)\n    rotateX(0)\n    # offset from center\n    translate(0, 50, 0)\n    # draw a white box outline at (0, 0, 0)\n    stroke(255)\n    box(50)\n    # the box was drawn at (0, 0, 0), store that location\n    x = modelX(0, 0, 0)\n    y = modelY(0, 0, 0)\n    z = modelZ(0, 0, 0)\n    # clear out all the transformations\n    popMatrix()\n    # draw another box at the same (x, y, z) coordinate as the other\n    pushMatrix()\n    translate(x, y, z)\n    stroke(255, 0, 0)\n    box(50)\n    popMatrix()\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "http://py.processing.org/reference/imgs/modelX0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
