
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Normal0Test extends E2eTestBase {

  public Normal0Test() {
    coreCodeTemplate = "settings <- function() {\n    size(100, 100, P3D)\n}\n\ndraw <- function() {\n    noStroke()\n    background(0)\n    pointLight(150, 250, 150, 10, 30, 50)\n    beginShape()\n    normal(0, 0, 1)\n    vertex(20, 20, -10)\n    vertex(80, 20, 10)\n    vertex(80, 80, -10)\n    vertex(20, 80, 10)\n    endShape(CLOSE)\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "https://processing.org/reference/images/normal_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
