
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Point1Test extends E2eTestBase {

  public Point1Test() {
    coreCodeTemplate = "# point 1 https://processing.org/reference/point_.html\n\nnoSmooth()\npoint(30, 20)\npoint(85, 20)\npoint(85, 75)\npoint(30, 75)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/point_0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
