
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Point2Test extends E2eTestBase {

  public Point2Test() {
    coreCodeTemplate = "# point 2 https://processing.org/reference/point_.html\n\nP3D <- \"processing.opengl.PGraphics3D\"\nsettings <- function() {\n    size(100, 100, P3D)\n}\n\ndraw <- function() {\n    noSmooth()\n    point(30, 20, -50)\n    point(85, 20, -50)\n    point(85, 75, -50)\n    point(30, 75, -50)\n    saveFrame(\"%s\")\n    exit()\n}\n";
    referenceURI = "https://processing.org/reference/images/point_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
