
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class QuadraticVertex2Test extends E2eTestBase {

  public QuadraticVertex2Test() {
    coreCodeTemplate = "# quadraticVertex 2 https://processing.org/reference/quadraticVertex_.html\n\nnoFill()\nstrokeWeight(4)\nbeginShape()\nvertex(20, 20)\nquadraticVertex(80, 20, 50, 50)\nquadraticVertex(20, 80, 80, 80)\nvertex(80, 60)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/quadraticVertex_1.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
