
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class RectMode0Test extends E2eTestBase {

  public RectMode0Test() {
    coreCodeTemplate = "CORNERS <- as.integer(1)\nCORNER <- as.integer(0)\n\nrectMode(CORNER) # Default rectMode is CORNER\nfill(255) # Set fill to white\nrect(25, 25, 50, 50) # Draw white rect using CORNER mode\n\nrectMode(CORNERS) # Set rectMode to CORNERS\nfill(100) # Set fill to gray\nrect(25, 25, 50, 50) # Draw gray rect using CORNERS mode\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/rectMode_0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
