
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Rotate0Test extends E2eTestBase {

  public Rotate0Test() {
    coreCodeTemplate = "PI <- pi\n\ntranslate(width/2, height/2)\nrotate(PI/3.0)\nrect(-26, -26, 52, 52)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/rotate_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
