
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Saturation1Test extends E2eTestBase {

  public Saturation1Test() {
    coreCodeTemplate = "noStroke()\ncolorMode(HSB, 255)\nc = color(0, 126, 255)\nfill(c)\nrect(15, 20, 35, 60)\nvalue = saturation(c)  # Sets 'value' to 126\nfill(value)\nrect(50, 20, 35, 60)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/saturation_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
