
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Smooth0Test extends E2eTestBase {

  public Smooth0Test() {
    coreCodeTemplate = "background(0)\nnoStroke()\nsmooth()\nellipse(30, 48, 36, 36)\nnoSmooth()\nellipse(70, 48, 36, 36)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "http://py.processing.org/reference/imgs/noSmooth0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
