
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Sqrt1Test extends E2eTestBase {

  public Sqrt1Test() {
    coreCodeTemplate = "noStroke()\na = sqrt(6561)  # Sets 'a' to 81\nb = sqrt(625)  # Sets 'b' to 25\nc = sqrt(1)  # Sets 'c' to 1\nrect(0, 25, a, 10)\nrect(0, 45, b, 10)\nrect(0, 65, c, 10)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/sqrt_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
