
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class StrokeJoin0Test extends E2eTestBase {

  public StrokeJoin0Test() {
    coreCodeTemplate = "MITER <- bitwShiftL(1, 3)\n\nnoFill()\nstrokeWeight(10.0)\nstrokeJoin(MITER)\nbeginShape()\nvertex(35, 20)\nvertex(65, 50)\nvertex(35, 80)\nendShape()\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/strokeJoin_0.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
