
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class StrokeCap0Test extends E2eTestBase {

  public StrokeCap0Test() {
    coreCodeTemplate = "ROUND <- bitwShiftL(1, 1)\nSQUARE <- bitwShiftL(1, 0)\nPROJECT <- bitwShiftL(1, 2)\n\nstrokeWeight(12)\nstrokeCap(ROUND)\nline(20, 30, 80, 30)\nstrokeCap(SQUARE)\nline(20, 50, 80, 50)\nstrokeCap(PROJECT)\nline(20, 70, 80, 70)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/strokeCap_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
