
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class StrokeWeight0Test extends E2eTestBase {

  public StrokeWeight0Test() {
    coreCodeTemplate = "strokeWeight(1)  # Default\nline(20, 20, 80, 20)\nstrokeWeight(4)  # Thicker\nline(20, 40, 80, 40)\nstrokeWeight(10)  # Beastly\nline(20, 70, 80, 70)\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/strokeWeight_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
