
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Tan1Test extends E2eTestBase {

  public Tan1Test() {
    coreCodeTemplate = "a = 0\ninc = TWO_PI/50\n\nfor (i in seq(0, 100, 2)) {\n    line(i, 50, i, 50 + tan(a) * 2)\n    a = a + inc\n}\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/tan_.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
