
// Generated by hack/generate-e2e-test.py
package test.e2e.core.function;

import static org.junit.Assert.fail;
import org.junit.Test;
import test.e2e.core.E2eTestBase;

public class Translate2Test extends E2eTestBase {

  public Translate2Test() {
    coreCodeTemplate = "rect(0, 0, 55, 55)  # Draw rect at original 0,0\ntranslate(30, 20)\nrect(0, 0, 55, 55)  # Draw rect at new 0,0\ntranslate(14, 14)\nrect(0, 0, 55, 55)  # Draw rect at new 0,0\n\nsaveFrame(\"%s\")\nexit()\n";
    referenceURI = "https://processing.org/reference/images/translate_2.png";
  }

  @Test
  public void test() {
    try {
      defaultOperation();
    } catch (Exception exception) {
      System.err.println(exception);
      fail("Should not have thrown any exception");
    }
  }
}
