category: Math
subcategory: Trigonometry
description: "
Converts a degree measurement to its corresponding value in radians. Radians and degrees are two ways of measuring the same thing. There are 360 degrees in a circle and 2*PI radians in a circle. For example, 90&deg; = PI/2 = 1.5707964. All trigonometric functions in Processing require their parameters to be specified in radians.
"
syntax: "radians(<c>degrees</c>)"
parameters:
  - label: 'degrees'
    description: "float: degree value to convert to radians"
related:
  - degrees
