category: Lights, Camera
subcategory: Camera
description: "
Sets a perspective projection applying foreshortening, making distant objects appear smaller than closer ones. The parameters define a viewing volume with the shape of truncated pyramid. Objects near to the front of the volume appear their actual size, while farther objects appear smaller. This projection simulates the perspective of the world more accurately than orthographic projection. The version of perspective without parameters sets the default perspective and the version with four parameters allows the programmer to set the area precisely. The default values are: perspective(PI/3.0, width/height, cameraZ/10.0, cameraZ*10.0) where cameraZ is ((height/2.0) / tan(PI*60.0/360.0));
"
syntax: "perspective()\nperspective(<c>fovy</c>, <c>aspect</c>, <c>zNear</c>, <c>zFar</c>)"
parameters:
  - label: 'fovy'
    description: "float: field-of-view angle (in radians) for vertical direction"
  - label: 'aspect'
    description: "float: ratio of width to height"
  - label: 'zNear'
    description: "float: z-position of nearest clipping plane"
  - label: 'zFar'
    description: "float: z-position of farthest clipping plane"
