category: PShape
subcategory: Method
description: "
Rotates a shape the amount specified by the <b>angle</b> parameter. Angles should be specified in radians (values from 0 to TWO_PI) or converted to radians with the <b>radians()</b> method.
<br /><br />
Shapes are always rotated around the upper-left corner of their bounding box. Positive numbers rotate objects in a clockwise direction. Transformations apply to everything that happens after and subsequent calls to the method accumulates the effect. For example, calling <b>rotate(HALF_PI)</b> and then <b>rotate(HALF_PI)</b> is the same as <b>rotate(PI)</b>. This transformation is applied directly to the shape, it's not refreshed each time <b>draw()</b> is run. 
"
syntax: "<c>sh</c>.rotate(<c>angle</c>)"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
  - label: 'angle'
    description: "float: angle of rotation specified in radians"
related:
  - rotateX
  - rotateY
  - rotateZ
  - scale
  - translate
  - resetMatrix
